services:
  postgresql:
      image: postgres
      environment:
        POSTGRES_USER: alunoimpacta
        POSTGRES_PASSWORD: 2301866
      ports:
        - 5432:5432

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: database
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: example
      MYSQL_PASSWORD: example
    ports:
      - 3306:3306